export * from "./landingPage";
export * from "./aboutUsPage";
export * from "./contactUsPage";
export * from "./newsPage";
export * from "./servicesPage";
export * from "./notFoundPage";
export * from "./servicesPage/productsDetails";
export * from "./newsPage/newsDetails";
export * from "./productsPage";